### PR TITLE
Update to Node.js 16 and new @actions/core

### LINKED ISSUE #84: Update to Node16 and new @actions/core
GitHub Actions is now giving deprecation warnings around this Action:

- [ ] Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: Azure/cli
- [ ] The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- [ ] The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### PR DESCRIPTION
**Pull request by tjcorr**
Fixes #84 to remove deprecation notices from this Action.

### CODE REVIEW

**Comment by NaveenTSW** [comment]
Still see this error for azure/CLI on Node12 version deprecation.

"Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: azure/CLI"

my action snippet got this which is complaining about Node12.
uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |

**Comment by tjcorr** [comment]
Looks like someone needs to cut a release and update the tags for this to get rolled out.

**Comment by NaveenTSW** [comment]
I see, thanks, not sure who cuts a release for this. @t-dedah any idea on that?

**Comment by t-dedah** [comment]
Hi @tjcorr why did we directly move to 16 instead of 14? Was there any particular reason for that?

**Comment by NaveenTSW** [comment]
@t-dedah any update on the new version?

**Pull request merged**
